language: android
sudo: required
dist: trusty # https://github.com/travis-ci/travis-ci/issues/3259
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra